name: Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['pypy3']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pypy3 -m pip install --upgrade pip
          pypy3 -m pip install pytest
      - name: Test with pytest
        run: |
          pypy3 -m pytest problems/*.py
